// data/products.ts

// 1. Define a consistent Product Type based on your actual data structure
export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  category: string;
  stock: number;
  rating: number;
  reviewCount: number;
}

// Map the keys for easier access later
export const sampleProducts: Record<string, Product[]> = {
  flower: [
    {
      id: 'flower-1',
      name: 'Blue Dream Premium',
      description: 'Classic sativa-dominant hybrid with sweet berry aroma',
      price: 45.99,
      image: '/products/blue-dream.jpg',
      category: 'flower',
      stock: 12,
      rating: 4.8,
      reviewCount: 156,
    },
    {
      id: 'flower-2',
      name: 'OG Kush',
      description: 'Legendary indica strain with earthy pine notes',
      price: 52.99,
      image: '/products/og-kush.jpg',
      category: 'flower',
      stock: 8,
      rating: 4.9,
      reviewCount: 203,
    },
    {
      id: 'flower-3',
      name: 'Sour Diesel',
      description: 'Energizing sativa with diesel and citrus flavors',
      price: 48.99,
      image: '/products/sour-diesel.jpg',
      category: 'flower',
      stock: 15,
      rating: 4.7,
      reviewCount: 142,
    },
    {
      id: 'flower-4',
      name: 'Purple Haze',
      description: 'Iconic strain with sweet berry and earthy tones',
      price: 55.99,
      image: "/products/purple-haze.jpg",
      category: 'flower',
      stock: 6,
      rating: 4.8,
      reviewCount: 178,
    },
    {
      id: 'flower-5',
      name: 'Girl Scout Cookies',
      description: 'Sweet and earthy hybrid with dessert-like flavor',
      price: 58.99,
      image: '/products/gsc.jpg',
      category: 'flower',
      stock: 10,
      rating: 4.9,
      reviewCount: 234,
    },
    {
      id: 'flower-6',
      name: 'Granddaddy Purple',
      description: 'Indica strain with grape and berry sweetness',
      price: 49.99,
      image: '/products/gdp.jpg',
      category: 'flower',
      stock: 14,
      rating: 4.6,
      reviewCount: 128,
    },
    {
      id: 'flower-7',
      name: 'Jack Herer',
      description: 'Balanced hybrid with spicy pine aroma',
      price: 51.99,
      image: '/products/jack-herer.jpg',
      category: 'flower',
      stock: 11,
      rating: 4.7,
      reviewCount: 167,
    },
  ],

  edibles: [
    {
      id: 'edible-1',
      name: 'Dark Chocolate Bar 100mg',
      description: 'Premium Belgian chocolate infused with pure extract',
      price: 24.99,
      image: '/products/chocolate-bar.jpg',
      category: 'edibles',
      stock: 25,
      rating: 4.8,
      reviewCount: 89,
    },
    {
      id: 'edible-2',
      name: 'Gummy Bears Assorted 200mg',
      description: 'Fruit-flavored gummies with precise dosing',
      price: 29.99,
      image: '/products/gummies.jpg',
      category: 'edibles',
      stock: 30,
      rating: 4.9,
      reviewCount: 312,
    },
    {
      id: 'edible-3',
      name: 'Fudge Brownies 50mg',
      description: 'Decadent chocolate brownies, individually wrapped',
      price: 19.99,
      image: '/products/brownies.jpg',
      category: 'edibles',
      stock: 18,
      rating: 4.7,
      reviewCount: 145,
    },
    {
      id: 'edible-4',
      name: 'Honey Toffee 150mg',
      description: 'Smooth toffee with natural honey infusion',
      price: 22.99,
      image: '/products/toffee.jpg',
      category: 'edibles',
      stock: 22,
      rating: 4.6,
      reviewCount: 76,
    },
    {
      id: 'edible-5',
      name: 'Chocolate Chip Cookies 100mg',
      description: 'Soft-baked cookies with real chocolate chips',
      price: 26.99,
      image: '/products/cookies.jpg',
      category: 'edibles',
      stock: 20,
      rating: 4.8,
      reviewCount: 198,
    },
    {
      id: 'edible-6',
      name: 'Mango Gummies 250mg',
      description: 'Tropical mango flavor with vitamin C',
      price: 32.99,
      image: '/products/mango-gummies.jpg',
      category: 'edibles',
      stock: 28,
      rating: 4.9,
      reviewCount: 267,
    },
    {
      id: 'edible-7',
      name: 'Caramel Bites 75mg',
      description: 'Rich caramel candy with sea salt',
      price: 18.99,
      image: '/products/caramel.jpg',
      category: 'edibles',
      stock: 15,
      rating: 4.5,
      reviewCount: 92,
    },
  ],

  vapes: [
    {
      id: 'vape-1',
      name: 'Hybrid Disposable Vape',
      description: 'Pre-filled disposable with hybrid strain blend',
      price: 35.99,
      image: '/products/disposable-vape.jpg',
      category: 'vapes',
      stock: 40,
      rating: 4.7,
      reviewCount: 234,
    },
    {
      id: 'vape-2',
      name: '510 Thread Cartridge - Indica',
      description: 'Premium indica oil in universal 510 cartridge',
      price: 42.99,
      image: '/products/510-cart.jpg',
      category: 'vapes',
      stock: 35,
      rating: 4.8,
      reviewCount: 178,
    },
    {
      id: 'vape-3',
      name: 'Shisha Flavored Pod',
      description: 'Exotic shisha flavors in convenient pod system',
      price: 28.99,
      image: '/products/shisha-pod.jpg',
      category: 'vapes',
      stock: 50,
      rating: 4.6,
      reviewCount: 156,
    },
    {
      id: 'vape-4',
      name: 'Laughing Gas Cartridge',
      description: 'Uplifting sativa blend for daytime use',
      price: 39.99,
      image: '/products/laughing-gas.jpg',
      category: 'vapes',
      stock: 28,
      rating: 4.9,
      reviewCount: 289,
    },
    {
      id: 'vape-5',
      name: 'Closed Loop Pod - Hybrid',
      description: 'Proprietary pod system with pure extract',
      price: 45.99,
      image: '/products/closed-pod.jpg',
      category: 'vapes',
      stock: 32,
      rating: 4.7,
      reviewCount: 167,
    },
    {
      id: 'vape-6',
      name: 'Live Resin Cartridge',
      description: 'Full-spectrum live resin in glass cartridge',
      price: 52.99,
      image: '/products/live-resin.jpg',
      category: 'vapes',
      stock: 24,
      rating: 4.9,
      reviewCount: 312,
    },
    {
      id: 'vape-7',
      name: 'CBD Disposable Pen',
      description: 'Pure CBD oil with natural terpenes',
      price: 29.99,
      image: '/products/cbd-pen.jpg',
      category: 'vapes',
      stock: 45,
      rating: 4.5,
      reviewCount: 134,
    },
  ],

  concentrates: [
    {
      id: 'concentrate-1',
      name: 'Premium Shatter 1g',
      description: 'Glass-like concentrate with 85% potency',
      price: 38.99,
      image: '/products/shatter.jpg',
      category: 'concentrates',
      stock: 16,
      rating: 4.8,
      reviewCount: 145,
    },
    {
      id: 'concentrate-2',
      name: 'Live Rosin 1g',
      description: 'Solventless extraction with full terpene profile',
      price: 65.99,
      image: '/products/rosin.jpg',
      category: 'concentrates',
      stock: 8,
      rating: 4.9,
      reviewCount: 198,
    },
    {
      id: 'concentrate-3',
      name: 'Bubble Hash 2g',
      description: 'Ice water extracted hash with high purity',
      price: 55.99,
      image: '/products/hash.jpg',
      category: 'concentrates',
      stock: 12,
      rating: 4.7,
      reviewCount: 112,
    },
    {
      id: 'concentrate-4',
      name: 'Crumble Wax 1g',
      description: 'Honeycomb textured wax for easy handling',
      price: 42.99,
      image: '/products/crumble.jpg',
      category: 'concentrates',
      stock: 14,
      rating: 4.6,
      reviewCount: 89,
    },
    {
      id: 'concentrate-5',
      name: 'Diamond Sauce 1g',
      description: 'THCA crystals in high-terpene sauce',
      price: 72.99,
      image: '/products/diamonds.jpg',
      category: 'concentrates',
      stock: 6,
      rating: 4.9,
      reviewCount: 223,
    },
    {
      id: 'concentrate-6',
      name: 'Budder 1g',
      description: 'Creamy concentrate with rich flavor',
      price: 45.99,
      image: '/products/budder.jpg',
      category: 'concentrates',
      stock: 10,
      rating: 4.7,
      reviewCount: 156,
    },
    {
      id: 'concentrate-7',
      name: 'Distillate Syringe 1g',
      description: 'Pure THC distillate for versatile use',
      price: 48.99,
      image: '/products/distillate.jpg',
      category: 'concentrates',
      stock: 18,
      rating: 4.8,
      reviewCount: 187,
    },
  ],

  beverages: [
    {
      id: 'beverage-1',
      name: 'Bissap Hibiscus Drink 100mg',
      description: 'Traditional West African hibiscus tea infusion',
      price: 12.99,
      image: '/products/bissap.jpg',
      category: 'beverages',
      stock: 35,
      rating: 4.6,
      reviewCount: 98,
    },
    {
      id: 'beverage-2',
      name: 'Tropical Cocktail Mix 150mg',
      description: 'Pre-mixed cocktail with exotic fruits',
      price: 18.99,
      image: '/products/cocktail.png', // NOTE: Original file was .png, kept it.
      category: 'beverages',
      stock: 28,
      rating: 4.7,
      reviewCount: 134,
    },
    {
      id: 'beverage-3',
      name: 'Amen Energy Drink 200mg',
      description: 'Energizing blend with natural caffeine',
      price: 15.99,
      image: '/products/amen.jpg',
      category: 'beverages',
      stock: 42,
      rating: 4.8,
      reviewCount: 201,
    },
    {
      id: 'beverage-4',
      name: 'Vim Wellness Shot 50mg',
      description: 'Concentrated wellness shot with vitamins',
      price: 9.99,
      image: '/products/vim.jpg',
      category: 'beverages',
      stock: 50,
      rating: 4.5,
      reviewCount: 87,
    },
    {
      id: 'beverage-5',
      name: 'Pineapple Juice 100mg',
      description: 'Fresh pineapple juice with tropical flavor',
      price: 13.99,
      image: '/products/pineapple.jpg',
      category: 'beverages',
      stock: 38,
      rating: 4.7,
      reviewCount: 156,
    },
    {
      id: 'beverage-6',
      name: 'Vanilla MilkShake 125mg',
      description: 'Creamy vanilla shake with premium ingredients',
      price: 16.99,
      image: '/products/milkshake.jpg',
      category: 'beverages',
      stock: 30,
      rating: 4.8,
      reviewCount: 178,
    },
    {
      id: 'beverage-7',
      name: 'Jojo Berry Blend 75mg',
      description: 'Mixed berry smoothie with antioxidants',
      price: 14.99,
      image: '/products/jojo.jpg',
      category: 'beverages',
      stock: 32,
      rating: 4.6,
      reviewCount: 112,
    },
  ],

  accessories: [
    {
      id: 'accessory-1',
      name: 'Premium Dab Pen',
      description: 'Temperature-controlled concentrate vaporizer',
      price: 89.99,
      image: '/products/dab-pen.jpg',
      category: 'accessories',
      stock: 15,
      rating: 4.8,
      reviewCount: 234,
    },
    {
      id: 'accessory-2',
      name: 'Glass Bong 12"',
      description: 'Borosilicate glass water pipe with ice catcher',
      price: 125.99,
      image: '/products/bong.jpg',
      category: 'accessories',
      stock: 8,
      rating: 4.9,
      reviewCount: 167,
    },
    {
      id: 'accessory-3',
      name: 'Titanium Grinder',
      description: '4-piece grinder with kief catcher',
      price: 34.99,
      image: '/products/grinder.jpg',
      category: 'accessories',
      stock: 45,
      rating: 4.7,
      reviewCount: 312,
    },
    {
      id: 'accessory-4',
      name: 'Rolling Papers Pack',
      description: 'Premium hemp papers with filters - 50 pack',
      price: 8.99,
      image: '/products/papers.jpg',
      category: 'accessories',
      stock: 100,
      rating: 4.6,
      reviewCount: 445,
    },
    {
      id: 'accessory-5',
      name: 'Portable Vaporizer',
      description: 'Dry herb vaporizer with digital display',
      price: 159.99,
      image: '/products/vaporizer.jpg',
      category: 'accessories',
      stock: 12,
      rating: 4.9,
      reviewCount: 289,
    },
    {
      id: 'accessory-6',
      name: 'Silicone Dab Mat',
      description: 'Non-stick mat for concentrate handling',
      price: 19.99,
      image: '/products/dab-mat.jpg',
      category: 'accessories',
      stock: 35,
      rating: 4.5,
      reviewCount: 123,
    },
    {
      id: 'accessory-7',
      name: 'Storage Container Set',
      description: 'Airtight UV-protected jars - 3 pack',
      price: 24.99,
      image: '/products/containers.jpg',
      category: 'accessories',
      stock: 28,
      rating: 4.7,
      reviewCount: 198,
    },
  ],
  snacks: [
    {
      id: 'accessory-1',
      name: 'Premium Dab Pen',
      description: 'Temperature-controlled concentrate vaporizer',
      price: 89.99,
      image: '/products/dab-pen.jpg',
      category: 'accessories',
      stock: 15,
      rating: 4.8,
      reviewCount: 234,
    },
    {
      id: 'accessory-2',
      name: 'Glass Bong 12"',
      description: 'Borosilicate glass water pipe with ice catcher',
      price: 125.99,
      image: '/products/bong.jpg',
      category: 'accessories',
      stock: 8,
      rating: 4.9,
      reviewCount: 167,
    },
    {
      id: 'accessory-3',
      name: 'Titanium Grinder',
      description: '4-piece grinder with kief catcher',
      price: 34.99,
      image: '/products/grinder.jpg',
      category: 'accessories',
      stock: 45,
      rating: 4.7,
      reviewCount: 312,
    },
    {
      id: 'accessory-4',
      name: 'Rolling Papers Pack',
      description: 'Premium hemp papers with filters - 50 pack',
      price: 8.99,
      image: '/products/papers.jpg',
      category: 'accessories',
      stock: 100,
      rating: 4.6,
      reviewCount: 445,
    },
    {
      id: 'accessory-5',
      name: 'Portable Vaporizer',
      description: 'Dry herb vaporizer with digital display',
      price: 159.99,
      image: '/products/vaporizer.jpg',
      category: 'accessories',
      stock: 12,
      rating: 4.9,
      reviewCount: 289,
    },
    {
      id: 'accessory-6',
      name: 'Silicone Dab Mat',
      description: 'Non-stick mat for concentrate handling',
      price: 19.99,
      image: '/products/dab-mat.jpg',
      category: 'accessories',
      stock: 35,
      rating: 4.5,
      reviewCount: 123,
    },
    {
      id: 'accessory-7',
      name: 'Storage Container Set',
      description: 'Airtight UV-protected jars - 3 pack',
      price: 24.99,
      image: '/products/containers.jpg',
      category: 'accessories',
      stock: 28,
      rating: 4.7,
      reviewCount: 198,
    },
  ],
};


export function getAllProducts(): Product[] {
  return Object.values(sampleProducts).flat();
}


export function getProductsByCategory(category: string): Product[] {
  return sampleProducts[category as keyof typeof sampleProducts] || [];
}