// data/products.ts

export interface Product {
  id: string;
  name: string;
  description: string;
  price: number;
  image: string;
  category: string;
  stock: number;
  rating: number;
  reviewCount: number;
}

export const sampleProducts: Record<string, Product[]> = {
  lipcare: [
    {
      id: 'lipcare-1',
      name: 'Brama Nourishing Lip Balm',
      description: 'Deeply hydrating balm infused with shea butter and vitamin E for soft, supple lips.',
      price: 29.99,
      image: '/products/lip-balm.jpg',
      category: 'lipcare',
      stock: 45,
      rating: 4.8,
      reviewCount: 210,
    },
    {
      id: 'lipcare-2',
      name: 'Brama Lip Scrub',
      description: 'Gentle exfoliating scrub with natural sugar crystals and coconut oil for smooth lips.',
      price: 24.99,
      image: '/products/lip-scrub.jpg',
      category: 'lipcare',
      stock: 38,
      rating: 4.7,
      reviewCount: 145,
    },
    {
      id: 'lipcare-3',
      name: 'Brama Tinted Lip Balm',
      description: 'Hydrating balm with a soft tint for a natural glow and protection throughout the day.',
      price: 34.99,
      image: '/products/tinted-lip-balm.jpg',
      category: 'lipcare',
      stock: 32,
      rating: 4.9,
      reviewCount: 186,
    },
    {
      id: 'lipcare-4',
      name: 'Brama Lip Mask',
      description: 'Overnight lip repair mask that restores and locks in moisture while you sleep.',
      price: 39.99,
      image: '/products/lip-mask.jpg',
      category: 'lipcare',
      stock: 28,
      rating: 4.8,
      reviewCount: 172,
    },
    {
      id: 'lipcare-5',
      name: 'Brama Lip Oil',
      description: 'Lightweight oil enriched with jojoba and rosehip for a glossy, nourished finish.',
      price: 35.99,
      image: '/products/lip-oil.jpg',
      category: 'lipcare',
      stock: 40,
      rating: 4.9,
      reviewCount: 195,
    },
  ],

  skincare: [
    {
      id: 'skincare-1',
      name: 'Brama Hydrating Face Cream',
      description: 'Daily moisturizer infused with aloe vera and hyaluronic acid for radiant skin.',
      price: 59.99,
      image: '/products/face-cream.jpg',
      category: 'skincare',
      stock: 25,
      rating: 4.8,
      reviewCount: 240,
    },
    {
      id: 'skincare-2',
      name: 'Brama Vitamin C Serum',
      description: 'Brightening serum that reduces dark spots and improves skin texture.',
      price: 69.99,
      image: '/products/vitamin-c-serum.jpg',
      category: 'skincare',
      stock: 20,
      rating: 4.9,
      reviewCount: 180,
    },
    {
      id: 'skincare-3',
      name: 'Brama Facial Cleanser',
      description: 'Gentle foaming cleanser with tea tree and cucumber extracts.',
      price: 39.99,
      image: '/products/cleanser.jpg',
      category: 'skincare',
      stock: 40,
      rating: 4.7,
      reviewCount: 198,
    },
    {
      id: 'skincare-4',
      name: 'Brama Night Repair Cream',
      description: 'Rich night cream that repairs and rejuvenates skin overnight.',
      price: 79.99,
      image: '/products/night-cream.jpg',
      category: 'skincare',
      stock: 18,
      rating: 4.9,
      reviewCount: 153,
    },
    {
      id: 'skincare-5',
      name: 'Brama Sunscreen SPF 50',
      description: 'Lightweight sunscreen providing broad-spectrum protection and hydration.',
      price: 49.99,
      image: '/products/sunscreen.jpg',
      category: 'skincare',
      stock: 36,
      rating: 4.8,
      reviewCount: 177,
    },
  ],

  makeup: [
    {
      id: 'makeup-1',
      name: 'Brama Liquid Foundation',
      description: 'Full-coverage foundation with a natural matte finish and SPF 25.',
      price: 69.99,
      image: '/products/foundation.jpg',
      category: 'makeup',
      stock: 30,
      rating: 4.8,
      reviewCount: 255,
    },
    {
      id: 'makeup-2',
      name: 'Brama Concealer Stick',
      description: 'Lightweight concealer that brightens and smooths under-eye areas.',
      price: 44.99,
      image: '/products/concealer.jpg',
      category: 'makeup',
      stock: 28,
      rating: 4.9,
      reviewCount: 192,
    },
    {
      id: 'makeup-3',
      name: 'Brama Lip Gloss',
      description: 'High-shine gloss enriched with argan oil for soft, luscious lips.',
      price: 29.99,
      image: '/products/lip-gloss.jpg',
      category: 'makeup',
      stock: 50,
      rating: 4.7,
      reviewCount: 225,
    },
    {
      id: 'makeup-4',
      name: 'Brama Setting Spray',
      description: 'Long-lasting mist that locks in makeup for up to 16 hours.',
      price: 35.99,
      image: '/products/setting-spray.jpg',
      category: 'makeup',
      stock: 35,
      rating: 4.8,
      reviewCount: 165,
    },
    {
      id: 'makeup-5',
      name: 'Brama Blush Palette',
      description: 'Vibrant shades for all skin tones with a smooth, blendable texture.',
      price: 49.99,
      image: '/products/blush.jpg',
      category: 'makeup',
      stock: 22,
      rating: 4.9,
      reviewCount: 210,
    },
  ],

  haircare: [
    {
      id: 'haircare-1',
      name: 'Brama Moisturizing Shampoo',
      description: 'Sulfate-free shampoo that cleanses while restoring hydration.',
      price: 39.99,
      image: '/products/shampoo.jpg',
      category: 'haircare',
      stock: 40,
      rating: 4.8,
      reviewCount: 205,
    },
    {
      id: 'haircare-2',
      name: 'Brama Deep Conditioner',
      description: 'Intensive repair formula for dry and damaged hair.',
      price: 44.99,
      image: '/products/conditioner.jpg',
      category: 'haircare',
      stock: 35,
      rating: 4.9,
      reviewCount: 190,
    },
    {
      id: 'haircare-3',
      name: 'Brama Hair Serum',
      description: 'Non-greasy serum that adds shine and reduces frizz.',
      price: 49.99,
      image: '/products/hair-serum.jpg',
      category: 'haircare',
      stock: 28,
      rating: 4.8,
      reviewCount: 156,
    },
    {
      id: 'haircare-4',
      name: 'Brama Hair Growth Oil',
      description: 'Infused with castor and rosemary oils to promote strong, healthy growth.',
      price: 59.99,
      image: '/products/hair-oil.jpg',
      category: 'haircare',
      stock: 25,
      rating: 4.9,
      reviewCount: 178,
    },
    {
      id: 'haircare-5',
      name: 'Brama Leave-In Conditioner',
      description: 'Lightweight spray for hydration, detangling, and shine.',
      price: 42.99,
      image: '/products/leave-in.jpg',
      category: 'haircare',
      stock: 33,
      rating: 4.8,
      reviewCount: 187,
    },
  ],

  fragrances: [
    {
      id: 'fragrance-1',
      name: 'Brama Bloom Eau de Parfum',
      description: 'Floral fragrance with jasmine, rose, and vanilla undertones.',
      price: 89.99,
      image: '/products/bloom.jpg',
      category: 'fragrances',
      stock: 20,
      rating: 4.9,
      reviewCount: 230,
    },
    {
      id: 'fragrance-2',
      name: 'Brama Noir Perfume',
      description: 'Bold, woody scent with amber and sandalwood notes.',
      price: 99.99,
      image: '/products/noir.jpg',
      category: 'fragrances',
      stock: 18,
      rating: 4.8,
      reviewCount: 190,
    },
    {
      id: 'fragrance-3',
      name: 'Brama Fresh Mist',
      description: 'Light citrus body mist perfect for everyday freshness.',
      price: 39.99,
      image: '/products/mist.jpg',
      category: 'fragrances',
      stock: 40,
      rating: 4.7,
      reviewCount: 165,
    },
    {
      id: 'fragrance-4',
      name: 'Brama Oud Essence',
      description: 'Luxurious Arabian oud blend with lasting aroma.',
      price: 119.99,
      image: '/products/oud.jpg',
      category: 'fragrances',
      stock: 12,
      rating: 4.9,
      reviewCount: 155,
    },
    {
      id: 'fragrance-5',
      name: 'Brama Citrus Bloom',
      description: 'Refreshing fragrance with orange blossom and bergamot.',
      price: 79.99,
      image: '/products/citrus-bloom.jpg',
      category: 'fragrances',
      stock: 25,
      rating: 4.8,
      reviewCount: 142,
    },
  ],

  bodycare: [
    {
      id: 'bodycare-1',
      name: 'Brama Shea Body Butter',
      description: 'Ultra-rich butter for deep nourishment and glowing skin.',
      price: 49.99,
      image: '/products/body-butter.jpg',
      category: 'bodycare',
      stock: 30,
      rating: 4.9,
      reviewCount: 212,
    },
    {
      id: 'bodycare-2',
      name: 'Brama Body Scrub',
      description: 'Exfoliating scrub that leaves your skin silky smooth and refreshed.',
      price: 39.99,
      image: '/products/body-scrub.jpg',
      category: 'bodycare',
      stock: 32,
      rating: 4.8,
      reviewCount: 189,
    },
    {
      id: 'bodycare-3',
      name: 'Brama Body Lotion',
      description: 'Hydrating lotion that keeps your skin soft and radiant all day.',
      price: 34.99,
      image: '/products/body-lotion.jpg',
      category: 'bodycare',
      stock: 40,
      rating: 4.7,
      reviewCount: 203,
    },
    {
      id: 'bodycare-4',
      name: 'Brama Shower Gel',
      description: 'Refreshing body wash with essential oils and aloe vera.',
      price: 29.99,
      image: '/products/shower-gel.jpg',
      category: 'bodycare',
      stock: 45,
      rating: 4.8,
      reviewCount: 175,
    },
    {
      id: 'bodycare-5',
      name: 'Brama Hand Cream',
      description: 'Non-greasy hand cream that restores moisture and softness.',
      price: 19.99,
      image: '/products/hand-cream.jpg',
      category: 'bodycare',
      stock: 50,
      rating: 4.9,
      reviewCount: 210,
    },
  ],
};

export function getAllProducts(): Product[] {
  return Object.values(sampleProducts).flat();
}

export function getProductsByCategory(category: string): Product[] {
  return sampleProducts[category as keyof typeof sampleProducts] || [];
}
